### ISSUE TITLE
How to set different time interval during autoscroll?

### ISSUE THREAD

**Issue by i0sdev** [gblancogarcia/GBInfiniteScrollView#39]
Tried to pass a `NSTimeInterval` value to  `self.infiniScrollView.interval`, but it's constant, not changed according to time settings for different scrolling pages.

My intention is to start auto scroll after "auto scroll" button pressed, then it could auto scroll at a flexible time interval which are linked to every scrolling page, because the shown time of every page is dynamic.

How to do that? Thanks!

**Comment by gblancogarcia** [comment]
Hey @942v,

You might try to do something like this in your view controller:

````
- (CGFloat)intervalAtIndex:(NSUInteger)index
{
    return self.infiniteScrollView.interval + 1;
}

- (void)infiniteScrollViewDidScrollNextPage:(GBInfiniteScrollView *)infiniteScrollView
{
    if (self.debug) {
        NSLog(@"Did scroll next page");
    }
    
    NSUInteger index = self.infiniteScrollView.currentPageIndex;
    self.infiniteScrollView.interval = [self intervalAtIndex:index];
    
    NSLog(@"Interval: %lu", (unsigned long)self.infiniteScrollView.interval);

    return self.shouldScrollNextPage;
}

- (void)infiniteScrollViewDidScrollPreviousPage:(GBInfiniteScrollView *)infiniteScrollView
{
    if (self.debug) {
        NSLog(@"Did scroll previous page");
    }
    
    NSUInteger index = self.infiniteScrollView.currentPageIndex;
    self.infiniteScrollView.interval = [self intervalAtIndex:index];
    
    NSLog(@"Interval: %lu", (unsigned long)self.infiniteScrollView.interval);
    return self.shouldScrollPreviousPage;
}

```

Cheers

**Comment by i0sdev** [comment]
`return self.shouldScrollPreviousPage` and `return self.shouldScrollNextPage` look not necessary in bottom two method. Right?

**Comment by gblancogarcia** [comment]
Yep. Sorry. Copy and paste. :smile:

**Comment by i0sdev** [comment]
Now it works! Thank you! Your'e very helpful.
