### ISSUE TITLE
GBInfiniteScrollViewPageStyleImage

### ISSUE THREAD

**Issue by brunojasgv** [gblancogarcia/GBInfiniteScrollView#46]
I have set the direction to GBAutoScrollDirectionRightToLeft with GBInfiniteScrollViewPageStyleImage, the problem is that when I scroll horizontally it bounces vertically by 20 pixels (the size of the status bar).

Here is my setup:

    self.autoScrollDirection = GBAutoScrollDirectionRightToLeft;
    self.infiniteScrollView = [[GBInfiniteScrollViewWithPageControl alloc] initWithFrame:self.myView.frame];
    self.infiniteScrollView.infiniteScrollViewDataSource = self;
    self.infiniteScrollView.infiniteScrollViewDelegate = self;
    self.infiniteScrollView.debug = self.debug;
    self.infiniteScrollView.verboseDebug = verboseDebug;
    self.infiniteScrollView.interval = 4.0f;
    self.infiniteScrollView.pageIndex = 0; //131 199 228
    self.infiniteScrollView.autoScrollDirection = self.autoScrollDirection;
    self.infiniteScrollView.scrollDirection = GBScrollDirectionHorizontal;
    self.infiniteScrollView.pageControlViewContainer.hidden = YES;
    [self.myView addSubview:self.infiniteScrollView];
    
    [self.infiniteScrollView reloadData];
    
    [self.infiniteScrollView startAutoScroll];

**Comment by brunojasgv** [comment]
I found a solution, it all works fine if I add this:

-(void)viewDidLayoutSubviews{
    self.automaticallyAdjustsScrollViewInsets = NO;
}

**Comment by 942v** [comment]
You should write that line of code in viewDidLoad, also if you are using storyboards you can set that flag there.

Guillermo Sáenz Urday
