### ISSUE TITLE
How to detect when scrolling has begun?

### ISSUE THREAD

**Issue by CVertex** [gblancogarcia/GBInfiniteScrollView#49]
I'm trying to figure out when's a good time to detect when the scrolling is done.

Any help is greatly appreciated

**Comment by gblancogarcia** [comment]
Hey @CVertex,

Have you try the ``GBInfiniteScrollViewDelegate`` protocol methods ``infiniteScrollViewDidScrollNextPage`` and ``infiniteScrollViewDidScrollPreviousPage``?

Cheers

**Comment by CVertex** [comment]
Thanks @gblancogarcia ! 

That works great for identifying when the scroll has _finished_, but I also want when the scroll is _starting_ 

From looking at the code, it looks like it's not supported at this stage. 

I'll try modifying the code and making a PR

**Comment by CVertex** [comment]
See https://github.com/gblancogarcia/GBInfiniteScrollView/pull/50
